---
apiVersion: v1
kind: Namespace
metadata:
  name: react-eks
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: react-eks
  name: deployment-react-eks
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: app-react-eks
  replicas: 2
  template:
    metadata:
      labels:
        app.kubernetes.io/name: app-react-eks
    spec:
      containers:
      - image: <AWS Account Id>.dkr.ecr.us-west-2.amazonaws.com/react-eks-app:latest
        imagePullPolicy: Always
        name: app-react-eks
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  namespace: react-eks
  name: service-react-eks
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  type: NodePort
  selector:
    app.kubernetes.io/name: app-react-eks
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  namespace: react-eks
  name: ingress-react-eks
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
spec:
  rules:
    - http:
        paths:
          - path: /*
            backend:
              serviceName: service-react-eks
              servicePort: 80